### ISSUE TITLE
Re-Calculate of Summary Results of “Functionality Status” to obtain Accurate Results consistent with Country-Level Results

### ISSUE THREAD

**Issue by MustafaAbdulrahmanWHO** [HeRAMS-WHO/herams-support#17]
**### Urgency: Normal**
**Describe the Enhancement** 
@SamuelPetragallo @JeffDotingco @luna404 @SamMousa 
Re-Calculate of Summary Results of “Functionality Status” to have consistent results in both the country-level analysis and the analysis of the visualization part of the new HeRAMS platform (i.e. use the same standard criteria followed at country-level by analyzing only “Government HFs” while excluding HFs under “Other HF-Type” classification).

**Brief description**
It is very important to ensure consistency between the Country-Level Analysis Results and the HeRAMS Analysis Results shown in the visualization part of the new HeRAMS platform. So, the visualization part of the new HeRAMS platform should follow the country criteria of selecting HFs to be analyzed (i.e. Analyze only “Government HFs” while excluding HFs under “Other HF-Type” classification).
-	Results provided by visualization part of new HeRAMS platform – Not Consistent with Country-Level Results are (55% Fully Functioning, 34% Partially Functioning, and 11% Non-Functioning)
-	Country-Level Results – obtained through analyzing only “Government HFs” while excluding HFs under “Other HF-Type” classification is (50% Fully Functioning, 35% Partially Functioning, and 15% Non-Functioning).

**Steps to reproduce the issue**
Change the Summary Analysis Results in the criteria of the visualization part so that it ensures analyzing only “Government HFs” while excluding HFs under the “Other HF-Type” classification.

**Expected behavior**
The Desired Action is to produce Summary HeRAMS Results with the following values (50% Fully Functioning, 35% Partially Functioning, and 15% Non-Functioning).

**Additional details**
-	The below screenshot shows non-accurate results of “Functionality Status” while the accurate results obtained when applying the standard country-level criteria by analyzing only “Government HFs” while excluding HFs under “Other HF-Type” classification is (50% Fully Functioning, 35% Partially Functioning, and 15% Non-Functioning).

![image](https://user-images.githubusercontent.com/65541276/85934667-ead86980-b8ee-11ea-98c0-0a1d57be0c7f.png)

Labels
Type: Enhancement
Urgency: Normal
Subject: Dashboard

**Comment by luna404** [comment]
@MustafaAbdulrahmanWHO the summary statistics presented in this pop-up intend to give an overview of data collected across different projects using a standardized approach. Limiting this to only include a subset of available data (in your case only including government facilities) would misrepresent the information collected and available through the HeRAMS platform. This would then create further issues as the summary statistics would no longer add up with the data presented at the workspace level or the project dashboard. 

As I mentioned before, this analysis is standardized across projects and any changes applied to it would affect all project. While we understand that this separation is important for Yemen, for other projects providing a comprehensive picture, including all facilities is crucial and is also one of the core principles of HeRAMS. We hope you can understand that due to reasons provided here, we won't be able to implement this request. 

Please note that dashboard already provides the necessary functionality to create summary statistics for only a subset of the data (i.e only government facilities and excluding HF type other). This should enable you to produce reports that are inline with the statics you are producing in country.
