### ISSUE TITLE
Auto-hide older versions of HF record 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#2]
Auto-hide older versions of HF record for HeRAMS Yemen. If an end user wants to edit the record of an HF, there is a record hidden for that specific facility which is the previous record.

**Comment by JeffDotingco** [comment]
Hi @ALKHSHBI, So I am starting to put issues raised by you in the excel file provided. Please let me know if fine with you

**Comment by luna404** [comment]
This issue will solve itself with the implementation of the new response picker.

Please note that we are currently working on an improved version of the HF table. Once implemented, multiple records for the same HF will be grouped together with the most recent record being on top. 

![image](https://user-images.githubusercontent.com/18245059/82649201-1cd41d00-9c19-11ea-97d3-087fdb94c132.png)

**Comment by MustafaAbdulrahmanWHO** [comment]
@luna404 @JeffDotingco @SamuelPetragallo @SamMousa Dear colleagues, I waited till you released the implementation of a new response maker and found that it may help in reducing some of the confusion by grouping multiple versions of same Health Facility together. However, please be informed that our request for "Auto-hiding of older versions of each Health Facility" while allowing the End-User to "Edit Only" will eliminate any chance for committing mistakes (i.e. editing the baseline data, creating duplicated versions of a health facility in a single month, not updating the last version of the health facility, etc.) and I hope that in the near future you will be able to fulfill our request.

**Comment by luna404** [comment]
As we mentioned previously, selective editing permissions (similar to role-based permissions to create/delete health facilities) is something that is currently not possible with LimeSurvey and is therefore not easy to develop. In addition, your request of limiting editing capabilities to the latest version of the record raises several process related challenges which we first have to resolve before we could invest in such a large-scale change.

1. > while allowing the End-User to "Edit Only"

	I assume you meant allowing users to only create an update and no longer be able to edit (overwrite) a record, otherwise how can users still add an update every month? While this is technically possible, we strongly advise against this. By disabling the edit button you create a huge risk of introducing duplicates and errors. You know as well as I that users do make mistakes while entering data. If you take away the option for them to correct mistakes or fill blanks, the only option they have is adding a new response. Thus, rather than solving the issue with duplicates; this will likely introduce more. In addition, if users add new responses as a method of correcting data you no longer now whether something was a true change, or a mistake entered. This will make trend analysis of your data extremely challenging. 
Also, when edit a record user already receive an explicit warning that they are overwriting a record. Together with adequate training this is process is working well in other countries. 

2. If you can only edit the latest version of a record, you further increase the risk of users creating duplicates. For example, if a user accidentally clicks on "add new record" instead of edit, they create a duplicate that they have no option to correct anymore. 

3.	Your proposed solution does not address the risk of users creating multiple records per month. Based on your desired workflow, users still need to be able to add a new record. As the date of update is manually entered by users (which is something that must remains as is or we would loose the ability to retrospectively add an update [for example, if I don't have internet access this week, it must be possible that I can retrospectively add this weeks' update next week when my internet connection has been established]), the system has no way of knowing for which month you would like to add a new record and whether or not it should allow you to create a new record. Moreover, while you might restrict updates to once a month in Yemen, this is something that we do not impose on other countries. The idea of HeRAMS is that data is updated whenever a change occurs which might also mean a facility is updated multiple times a month. 
4.	Regarding updating the latest version of the health facility. If a user chooses to add a new response, this is always based on the lasted version. So there is no need for you to worry about that part. In addition, records are order by date with the latest version always on top. Please note while you can sort or filter health facilities by date, this does not affect responses to a given facility. Thus, if users do need to edit (overwrite) a record, it should be feasible to train them to pay attention to the date column to make sure they are editing the correct version.

**Comment by MustafaAbdulrahmanWHO** [comment]
@luna404 Please be informed that what I meant is to automatically hide the older versions of each HF while keeping both "Update" and "Edit" buttons active (i.e. only the last version of each HF is shown and once the user clicks the "Update" button to create a new response based on the last version of HF, that baseline version of the HF is automatically hidden and only the new response will be visible to the user) and whenever the user needs to make any changes, he could easily use the "Edit" button. Anyhow, Samuel Petregallo has already informed me that this request couldn't be fulfilled using the current platform and hope it could be possible in the future as this will eliminate potential mistakes that users usually make.
