### ISSUE TITLE
Solve problem of blank rows exported

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#3]
Solve problem of blank rows exported (p.s. Related to the 3 comment boxes)

@ALKHSHBI, kindly provide a screenshot of the blank row so that we can replicate it. Or this is about blank columns?

**Comment by MustafaAbdulrahmanWHO** [comment]
@JeffDotingco, please be informed that this issue is not related to the "Blank Columns" issue. This problem is related to "Frontend Export" because when exporting some blank rows appear in the exported file (I traced the blank records and found that they are caused when the user "Press Enter/Insert NewLine in any of the Comment Boxes: Address, HWs details, and Comment Box at the end of the survey.

**Comment by JeffDotingco** [comment]
need more info on this @MustafaAbdulrahmanWHO with the improved excel frontend data exporting.

**Comment by MustafaAbdulrahmanWHO** [comment]
@JeffDotingco I think this problem still exist with ".CSV" Frontend Export (when the enumerator insert "NewLine" in any of the 3 Text Boxes: Address, HWs details, and Comment Box at the end of the survey).

**Comment by luna404** [comment]
@MustafaAbdulrahmanWHO I can't reproduce this error. Could clarify what language you select and whether you export data as code or text. 

Also, it seems the issue is with Excel and not the CSV file itself. When I open the CSV file in another application I don't see any issue with unwanted line-breaks. We are aware that Excel sometimes has issues properly reading CSV files. This is why we added the option to download the data as Excel file. If you are analysing the data in Excel, we recommend you download the data as Excel file.

**Comment by MustafaAbdulrahmanWHO** [comment]
@luna404 Please be informed that the "Blank Rows Export" in".CSV" Frontend Export. Moreover, the problem of Frontend Export to ".CSV" when switching on "Question Text Header" is also still not solved. Please find in the attached sample of the "Blank Row Export" problem.  I have also attached a file showing the problem of Frontend Export to CSV - when Switching ON the "Question Text Header".
[Export to CSV - Text Header ON.xlsx](https://github.com/HeRAMS-WHO/herams-support/files/4898378/Export.to.CSV.-.Text.Header.ON.xlsx)

[Sample of Blank Rows Export CSV.xlsx](https://github.com/HeRAMS-WHO/herams-support/files/4898337/Sample.of.Blank.Rows.Export.CSV.xlsx)

**Comment by luna404** [comment]
@MustafaAbdulrahmanWHO your first point on the header not being readable in the Arabic export, this is an encoding issue on your side. Excel does not default to UTF-8 but I think uses Latin1 as default encoding. For Arabic text you need to change this to UTF-8 otherwise characters will appear unreadable. Please check out the user guide if you need help changing the encoding https://docs.herams.org/en/latest/#data-encoding-in-excel.

Regarding the blank row, I just downloaded the data and imported it into Excel. I don't like share the entire data set here, but I can send it to you by email. As you can see in the screenshot below, I don't have any issues with blank rows for the record in question

![image](https://user-images.githubusercontent.com/18245059/87155456-46293500-c2bb-11ea-9487-2159f43bc22a.png)

May I ask how you are opening the CSV file? Please try to read in the CSV file as shown in the user guide (Data -> read from CSV/Text). 

In any case if you are using Excel to analysis the data, may I ask why you are not using the Excel export function? Is there a problem with it?
