### ISSUE TITLE
Limit Add/Remove HF to Admin account

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#8]
Currently, an admin user has to go to backend account and configure settings in order to Enable create and delete button in the plugins section. Is there a way in the HeRAMS platform to limit "Add/Remove HF" to admin users only once these features are activated in LS that can only be seen by users with admin access and not all users?

**Comment by luna404** [comment]
The current permission system does not allow assigning create and delete permissions based on a user roles. As this is due to limitation imposed by LimeSurvey itself, it is not something we will be able to address at this stage. 

However, we are planning some major changes to the management of health facilities in HeRAMS. The idea is that the MHFL is managed directly in HeRAMS and longer through LS. Once this has been implemented will be able to develop a more granular permission system allowing to limit the creation and deletion of health facilities.

**Comment by luna404** [comment]
Workaround has been implemented. Proper solution will come with HeRAMS V2
