### ISSUE TITLE
Add "view/read-only" as a workspace privilege

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#9]
Add "view/read-only" as a workspace privilege

For clarification @ALKHSHBI. Please find below:

![WS2](https://user-images.githubusercontent.com/50957748/82414837-3a36a900-9aaa-11ea-8a94-386868984ca4.png)

**Comment by luna404** [comment]
On your first point, this is an enhancement that we are planning on developing. However, please note that this requires substantial development work and it might take some time before this is being implemenetd.

On point two, @ALKHSHBI, could you please provide a use case why users need to view individual records without the ability to edit them. 

From our point of view, users who do not have permissions to edit the data should use the dashboard to access the desired information. By applying filters and printing the dashboard reports, it is already possible to gain in-depth information on specific subsets of the data.

Please note there is currently no "view" permission that permits users to view individual records. Editing and view data is closely tight together and separating these permissions would take substantial development. However, a partial workaround to this issue is available. Edit and download permission are managed separately. This means you could grant a user permission to download workspace level data to view individual records without granting them the ability to edit the data.

**Comment by luna404** [comment]
Can't be fixed with LS, will come with HeRAMS V2
